return {
--     "nvim-tree/nvim-tree.lua",
--     config = function()
--         require("nvim-tree").setup({
--             sort = {
--                 sorter = "case_sensitive",
--             },
--             view = {
--                 adaptive_size = true
--             },
--             renderer = {
--                 group_empty = true,
--             },
--             filters = {
--                 dotfiles = true,
--             },
--             git = {
--                 ignore = false,
--             },
--         })
--         vim.keymap.set("n", "<leader>ee", "<cmd>NvimTreeToggle<CR>", { desc = "Toggle file explorer" }) -- toggle file explorer
--         vim.keymap.set("n", "<leader>ef", "<cmd>NvimTreeFindFileToggle<CR>", { desc = "Toggle file explorer on current file" }) -- toggle file explorer on current file
--         vim.keymap.set("n", "<leader>ec", "<cmd>NvimTreeCollapse<CR>", { desc = "Collapse file explorer" }) -- collapse file explorer
--         vim.keymap.set("n", "<leader>er", "<cmd>NvimTreeRefresh<CR>", { desc = "Refresh file explorer" }) -- refresh file explorer
--
--         vim.cmd('highlight NvimTreeNormal guibg=NONE ctermbg=NONE')
--     end,
}
