return {
    -- {
    --     "mfussenegger/nvim-lint",
    --     event = {
    --         "BufReadPre",
    --         "BufNewFile",
    --     },
    --     config = function()
    --         local lint = require("lint")
    --         local checkstyle = require("lint.linters.checkstyle")
    --         lint.linters_by_ft = {
    --             java = { "checkstyle" },
    --             javascript = { 'eslint_d' },
    --             javascriptreact = { 'eslint_d' },
    --             typescript = { 'eslint_d' },
    --             typescriptreact = { 'eslint_d' },
    --         }
    --         -- checkstyle.config_file = ""
    --
    --         local lint_augroup = vim.api.nvim_create_augroup("lint", { clear = true })
    --
    --         vim.api.nvim_create_autocmd({ "BufEnter", "BufWritePost", "InsertLeave" }, {
    --             group = lint_augroup,
    --             callback = function()
    --                 lint.try_lint()
    --             end,
    --         })
    --
    --         vim.keymap.set("n", "<leader>ll", function()
    --             lint.try_lint()
    --         end, { desc = "Trigger linting for current file" })
    --     end,
    -- },
}
